### ISSUE TITLE
Trying to use this example

### ISSUE THREAD

**Issue by kelfink** [ncarlier/kong-integration-samples#3]
https://github.com/kelfink/kong-konga-cognito-docker/issues/1

I've grabbed this docker-compose.yml file and made a switch to just rely on the "kong:latest" image for kong, instead of a local build, and not using your ncarlier build.  Not sure why but lots of errors.    Do I need to be using your image for this to work?  See errors at issue.  thanks, and sorry it's a bit off topic to our repo.

**Comment by ncarlier** [comment]
It's because of the `KONG_CUSTOM_PLUGINS` env variable. Kong try to load the `oidc` plugin. But the official Kong image don't have this plugin. It's the ONLY purpose of my build: Add the Nokia OpenID Connect to the official image. So if you want to use the official image without this plugin you have also to unset the `KONG_CUSTOM_PLUGINS` env variable.
